gText_ObtainedTheItem::
	.string "Obtained the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"
    
gText_ObtainedTheItems::
    .string "Obtained {COLOR GREEN}{STR_VAR_1} {STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TheBagIsFull::
	.string "The Bag is full…$"

gText_PutItemInPocket::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} put away the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in the {COLOR GREEN}{STR_VAR_3}{COLOR DARK_GRAY} Pocket.$"

gText_PlayerFoundOneItem::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} found one {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_PlayerFoundItems::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} found {COLOR GREEN}{STR_VAR_1} {STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag::
	.string "{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY} put away the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in the Bag.$"

gText_ObtainedTheDecor::
	.string "Obtained the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY} was transferred\n"
	.string "to the PC.$"
